service: action-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

resources:
  - ${file(resources/CognitoUserPool.yml)}
  - ${file(resources/ApiMain.yml)}
  - ${file(resources/ApiAuthorizer.yml)}

custom:
  AppName: AuctionApp
